spring:
  application:
    name: BoardBuddy
#  profiles:
#    active: common
#  config:
#    activate:
#      on-profile: "common"
  config:
    location: file:/config/
  sql:
    init:
      platform: mariadb
      mode: always
      data-locations: classpath:data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: naver
            redirect-uri: https://boardbuddyapp.com/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: google
            redirect-uri: https://boardbuddyapp.com/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            redirect-uri: https://boardbuddyapp.com/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname,account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG

